### ISSUE TITLE
Create documentation for reconciler

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#168]
**Description**

The reconciler requires a documentation which covers the

* goals and requirements (function, non-functional)
* architecturel view (components, their purpose, how the interact, made decisions, known risks)
* operational view (configuration options, deployment model, integration with SRE systems etc.)
* component view (description of component-reconcilers and mothership reconciler)

**Area**

* Mothership reconciler
* Component reconciler

**Reasons**

Fulfil documentation requirements

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by NHingerl** [comment]
I think we need one or more new topics under [Administration and Operations in the Kyma Environment](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/b8e16869e64a4abe93cc194aa6fdacf5.html). 
One page describing what the reconciler is, its purpose, architecture and components. And maybe another one if we want to provide any instructions what users can do with it.

**Comment by NHingerl** [comment]
Call with @tobiscr
- for customers, we need general information in SAP help portal that Kyma as a managed service will update and revert customer changes automatically, in order to keep SLAs, have the latest version etc.
- also, we should have disclaimers directly with any resource that is managed by Kyma and must not be changed by the customer - for resources created by reconciler as well as for any others managed by Kyma (see [Slack](https://sap-btp.slack.com/archives/G01TZANCEE8/p1631796606035600) and https://github.com/kyma-incubator/reconciler/issues/170)
- for internal documentation (target group: Kyma), Tobias and the team will provide drafts to review.

**Comment by NHingerl** [comment]
Draft for the disclaimer, which we put as a Note in [Kyma Environment](https://help.sap.com/viewer/DRAFT/60f1b283f0fd4d0aa7b3f8cea4d73d1d/Internal/en-US/468c2f3c3ca24c2c8497ef9f83154c44.html):

> Kyma as a managed service automatically checks all Kyma-managed resources. Any unexpected modifications are discarded and the resource is reverted to the original state.
