### ISSUE TITLE
Auditlog: Log http calls to mothership-reconciler in audit-log system

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#291]
**Description**

As part of the threat modelling, we identified that any crititcal action a user or 3rd party  applies on the mothership reconciler has to be documented. 

Critical actions are:

* Security events (failed logins -> has to happen by ORY, **has to be confirmed with SRE!!**)
* Updating cluster data (writes to cluster inventory e.g. any calls from KEB + status-update made by user for disabling/enabling a cluster for reconciliation)

To achieve this requirement, any received HTTP request has to be tracked in the SAP Auditlog system (alternative could be a GPC bucket which allows only appending data).

The log message has to include the user-ID and the applied action.

AC:

* Audit messages are stored in an non-modifyable storage (e.g. SAP Auditlog service) for each received HTTP request and include user-ID + description of the applied action.
* Audit logs have to be stored for max. 180 days (retention time has to be configurable)

**Reasons**

Fulfil security expectations.

**Attachments**

**Comment by moelsayed** [comment]
Status update:
- The main reconciler PR is merged.
- A PR for control-plane charts is ready for review kyma-project/control-plane#1059
- A small follow up PR to fix an issue with logging format is in progress 

Regarding the implementation and requirements:
- Authz/Authn is currently handled by istio not Ory. However, it's possible to log failed logins and unauthorized access attempts in this implementation since this is handled outside the mothership reconciler.
- Logs are stored on a PV and shipped using fluentbit to the SAP Audting system
- Logs are persisted across restarts/crashes. 
- Authenticated requests will show the user-id `sub` in the token payload passed by istio. 
-

**Comment by moelsayed** [comment]
Status update:
- At this point all PRs are in review stage. During testing the Audit backend seems to be accepting the shipped logs, however, they are displayed on the log viewer. We are currently investigating that cc: @rakesh-garimella

**Comment by kwiatekus** [comment]
Fixes for most of review comments pushed on the reconciler audit log PR
Debugging a failed tests on the charts PR
Tiny fix for using busybox from our gcr is still [pending](https://github.com/kyma-project/control-plane/pull/1059/files#r750045402)
