### ISSUE TITLE
Status of the current reconciliation run affects all of the historical entries when inspected via CLI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-incubator/reconciler#364]
**Description**

Status of reconciliations are affected by current reconciliation state.
I.e 
 - If reconciler runs against a runtime, all reconciliation runs appear with status `reconciling`
 - Once the reconciliation is done all entries ( the last one and all historical ) are set to `ready`

**Expected result**

Only the state of the current run should be shown as `reconciling`. Historical entries should preserve status

**Actual result**

All entries of a given cluster appear as`reconciling` at the time of reconcilation

**Steps to reproduce**

Run 
`kcp reconciliations -c {your shoot cluster} --config {path to config}`
and observe changes as a reconciler picks your cluster up

**Troubleshooting**

**Comment by Cortey** [comment]
@tobiscr, @kwiatekus 
We are always taking the last status of cluster for reconciliation due to usage of GetLatest() in the [method](https://github.com/kyma-incubator/reconciler/blob/aa4dd8c3c796b1b9ac3a298882232dd007471e28/cmd/mothership/mothership/start/http.go#L312). We need to enhance the database model to track the status of reconciliations in a separate [field here](https://github.com/kyma-incubator/reconciler/blob/aa4dd8c3c796b1b9ac3a298882232dd007471e28/pkg/model/reconciliationentity.go#L12).

**Comment by varbanv** [comment]
This change caused: https://github.tools.sap/kyma/backlog/issues/2035 but this item is complete.
