### ISSUE TITLE
Reconciler does not change deployed resources anymore

### ISSUE THREAD

**Issue by skhalash** [kyma-incubator/reconciler#368]
**Description**

When testing reconciler-based installation with `kyma deploy` I stumbled upon the following bug. 
If Kyma is installed on the cluster, then changing its configuration does not work (I tried setting overrides or making changes directly in the workspace where the charts are loaded from). Reconciler returns successfully, but the cluster state remains unchanged.

By going revision-per-revision I found out that the bug is introduced by https://github.com/kyma-incubator/reconciler/pull/337. The previous revision works fine.

**Steps to reproduce**

1. Create a new k3d cluster.
2. Install Kyma `main` by running `kyma deploy`
3. Create an override file and store it as `logging.yaml`
```yaml
logging:
  loki:
    config:
      limits_config:
        ingestion_rate_mb: 1
```
4. Run `kyma deploy --component logging --value-file logging.yaml`. Note that it is just an example - none of the options that change Kyma configuration will work (`--values`, `--domain`, `--tls-cert`, `--tls-config`, as well as making changes directly in the workspace where the charts are loaded from).

**Expected result**

Loki's configuration will be changed, it will trigger a rolling update of Loki StatefulSet.

**Actual result**

Nothing happens, reconciler returns successfully, cluster's state remains unchanged.

**Comment by tobiscr** [comment]
QQ: we were searching for the `ingestion_rate_mb` and couldn't find it in the HELM chart of loki. Are you sure this parameter will cause a change in the manifests?

**Comment by skhalash** [comment]
Yeah, I am sure, it worked fine before #337 was merged. You can verify this value by pulling Loki's config from the secret:
```
kubectl get secrets -n kyma-system logging-loki -oyaml
```

As I wrote above, it can be any other configuration change in any other component.

**Comment by m00g3n** [comment]
@skhalash any chance you could provide a `yaml` with the resource that leads to this bug?

**Comment by kwiatekus** [comment]
In my case the `replace` strategy covered this [problem](https://github.com/kyma-project/kyma/issues/12531)

There are helm functions applied to generate certs - therefore rendering cluster-essential manifests produce new values for 
 - `caBundle` of `cluster-essentials-pod-preset-webhook`
 - data of `cluster-essentials-pod-preset-webhook-cert` secret
 AND ( due to changes in the above )
  - `checksum/config` annotation of the deployment `cluster-essentials-pod-preset-webhook` template
  
  you can see that by rendering manifests with local helm client in the `cluser-essentials` chart folder
  `helm template . > manifests.yaml` ( please find attached manifest )
  
[manifests_yaml.txt](https://github.com/kyma-incubator/reconciler/files/7511542/manifests_yaml.txt)

  
With a new replace strategy this manifest results with no redeployment of `cluster-essentials-pod-preset-webhook`  deployment

**Comment by kwiatekus** [comment]
The common pattern in @skhalash case and mine is the usage of `checksum/config` annotation to rollout new deployments based on changes in configuration.
Seems there is a problem with that in combination with replace strategy in reconciler

Those [cases](https://github.com/kyma-project/kyma/search?q=checksum%2Fconfig) will be affected.

**Comment by skhalash** [comment]
As discussed, the actual configmaps/secrets are not getting updated, that's why the checksum remains the same.
