### ISSUE TITLE
Align with KEB the way of passing authentication credentials to reconciler to get rid of secret-lookups inside of reconciler library

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#418]
**Description**

Currently the reconciler is retrieving authentication credentials for Github access (e.g. when accessing an SAP internal Github) by doing secrete lookups and getting the authentiation data from the secret (See git-lib implementation in reconciler).

This was implemented because we don't want to store senstiive data later on SKR clusters (e.g. when dumping  the configuration of the cluster on the target cluster, see #334 )

This is not a good approach for two reasons:

* We are also publishing the reconciler library also as open-source product and we should avoid logic which couples the library to company internal deployment agreements
* The configuration stored on the SKR should in general be not public readable and properly encrypted (e.g. via AES). Only the mothership reconciler should be allowed to read it

AC:
* Credentials should be passed as regular configuration parameters via the component-configuration from KEB
* Remove secret-lookup logic in reconciler API (See git-lib and download logic in workspace-factory)

**Reasons**

Avoid deployment specific logic in reconciler lib (authentication credential lookups).

**Attachments**

**Comment by janmedrek** [comment]
For the Connectivity Proxy reconciler:
- The config should be passed by KEB through Reconciler's [external API](https://github.com/kyma-incubator/reconciler/blob/518113af8c11359bc4c474ef9d774f8da4d42903/openapi/external_api.yaml#L733)
- There is configuration file available for the whole Kyma Control Plane - it is the proper place to put the config

Also, @tobiscr, is there any sub-reconciler other than Connectivity Proxy that uses K8S underneath?

**Comment by tobiscr** [comment]
The reason for this ticket was, that we couple the reconciler to some K8s resources . The reconciler code should acutally not use for internal decisions/purposes any resources from K8s as we are also running it for testing-purposes the reconciler outside of K8s.

It's fine when comp-reconcilers are interacting with a remote K8s cluster, but they should not be use K8s resources to work internally correctly.

**Comment by piotrmiskiewicz** [comment]
My 2 cents. If we move the secret management from Reconciler to KEB, we have the same problem as you, in the Reconciler. I do not see any advantage, only disadvantage - additional fields in the API. There is no any difference between Reconciler and KEB - we have both deployed on k8s.

**Comment by piotrmiskiewicz** [comment]
AS I understand, the secret should be mounted in a deployment definition in a reconciler chart.

**Comment by tobiscr** [comment]
biggest difference is that the reconciler has also to work outside of K8s (e.g. KYma CLI). that's why looking up some K8s secrets isn't working for us.

**Comment by franpog859** [comment]
We need to have a confidential token in the Component Reconciler:
- the Reconciler is also used outside of the k8s runtime so we cannot use any k8s resources, for example, Secrets. Therefore, current implementation needs to be changed as it, in fact, uses k8s Secretes
- the token cannot be built into the Component Reconciler as [the `ISTIOCTL_PATH`](https://github.com/kyma-incubator/reconciler/blob/main/Dockerfile.cr#L43) is, because it's confidential and cannot be publicly exposed

The things I (as a non-Reconciler and non-KEB developer :D) would consider are:
1. using the [Component Reconciler configuration API](https://github.com/kyma-incubator/reconciler/blob/main/openapi/external_api.yaml#L744-L747) in the KEB so it passes the confidential token in the request. The token could be stored in _some internal hypothetical management plane config_
2. [mounting a k8s Secret to the Component Reconciler as an environment variable](https://github.com/kyma-project/control-plane/pull/1424/files) if the config is set in _some internal hypothetical..._ It could be set as a normal environment variable so I assume it won't be an issue for the Kyma CLI

**Comment by janmedrek** [comment]
@franpog859 I believe that we should mount the secret as an env variable. There are voices that the charts of Connectivity Proxy may be hosted somewhere in public - that would be great since we will be able to drop that secret at all.

In this case, I would recommend going with the simplest solution, as it seems like it will be only temporary.
