### ISSUE TITLE
Ory Postgresql upgrade is not working properly

### ISSUE THREAD

**Issue by cnvergence** [kyma-incubator/reconciler#459]
**Description**
We should be able to reconcile Postgresql in the Ory helm chart when we are changing its configuration, like the image version. I have already checked that it is not related to the fact, that PostgreSQL helm chart is the dependency of Ory, as the Rafter helm chart is working properly.

**Expected result**
Currently when updating PostgreSQL values in the Helm chart, like image version, and running reconcile action again won't perform the update action on Ory PostgreSQL StatefulSet.

**Actual result**
Updating PostgreSQL values in the Helm chart, like the image version, and running reconcile action again should perform the update action on Ory PostgreSQL StatefulSet.

**Steps to reproduce**
Install Ory component with reconciler on older PostgreSQL version, change the version of PostgreSQL to the newer and run the reconciler again.

**Troubleshooting**

**Comment by cnvergence** [comment]
Checked also update strategy and it is set to _Update Strategy: RollingUpdate_, as it should be.

**Comment by mjakobczyk** [comment]
I analysed a behaviour of the Reconciler with PostgreSQL sub chart of Ory. StatefulSet resource is defined here: https://github.com/kyma-project/kyma/blob/main/resources/ory/charts/postgresql/templates/statefulset.yaml

It is not possible to update it with the default reconciliation logic once it is uploaded on the cluster. It was not possible to update it with `kubectl apply` as well. The official k8s documentation suggests performing `patch` in order to make use of `Rolling Update`: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#rolling-update This logic could be handled by each component individually, but - in general - this should be a supported solution out of the box because we have at least 6 or 7 different components that use `StatefulSet`.

**Comment by tobiscr** [comment]
Hi @mjakobczyk , yes that's known issue we currently have: replace with PVCs involved doesn't work out (that's why also StatefulSets are not replaced as soon as they include PVCs in their manifest).

If this is a show-stopper for Kyma 2.0, we have to enhance our kubeclient to use PATCH for PVC-related manifests.

**Comment by tobiscr** [comment]
Will be addressed in https://github.com/kyma-incubator/reconciler/issues/465

**Comment by pbochynski** [comment]
Let's track it here: https://github.com/kyma-incubator/reconciler/issues/465
