### ISSUE TITLE
Reconciler uses per default evaluation profile

### ISSUE THREAD

**Issue by veichtj** [kyma-incubator/reconciler#609]
**Description**

When I install Kyma 2.0 with reconciler without passing a profile, reconciler uses per default the evaluation profile.
The Kyma cli has a different behaviour, it just uses the default values out of the values.yaml files.

**Expected result**

Reconciler and Kyma cli have the same behaviour if no profile is passed.

**Actual result**

If no profile is passed then evaluation profile is used.

**Steps to reproduce**

-cli: `kyma install --source=1-24.8`
-reconciler: `./bin/mothership-darwin local --value=global.domainName=some.domain.com`

**Troubleshooting**

N/A

**Comment by Tomasz-Smelcerz-SAP** [comment]
By "When I install Kyma 2.0 with reconciler" I assume we're reffering to the mentioned `mothership-darwin local` command.  This command is fixed with #611 and it no longer uses the evaluation profile.
As for pipelines we are using evaluation profile explicitly for Kyma1 installation, and the same profile is used for reconciling Kyma 2.0 with reconciler - it's embedded in the mothership configuration files.
Please also take a look at: https://github.com/kyma-incubator/reconciler/issues/620
