### ISSUE TITLE
Istio reconciler should support istio and istio-configuration pre-req components

### ISSUE THREAD

**Issue by strekm** [kyma-incubator/reconciler#698]
**Description**

For a time of supporting kyma 2.0.x and kyma 2.1.x istio custom reconciler should support both kyma components: [istio](https://github.com/kyma-project/kyma/issues/13114) for kyma 2.1.x / main installation and istio-configuration for kyma 2.0.x installation. Difference in logic is quite small and in case of istio-configuration additional resources should be created but in case of istio component this should be skipped.

AC:
- [x] actions registered for both istio-configuration & istio
- [x] implemented logic which determines whether to apply additional resources or not
- [x] when `istio` component is not present in resources then error is thrown

**Reasons**

Getting rid of technical debt

**Attachments**

part of https://github.com/kyma-incubator/reconciler/issues/543

**Comment by mjakobczyk** [comment]
Review of [PR](https://github.com/kyma-incubator/reconciler/pull/704) - this solution does not work, so I rejected it. 🔴 
To sum up Acs:
✅ 1. `actions registered for both istio-configuration & istio` - OK, there are two different actions registered
🚫  2. `implemented logic which determines whether to apply additional resources or not` - not in place
🚫 3. `README.md updated` - no README has been updated so far

My observations so far:
1. Reconciliation of `istio-configuration` component
Command used: `./bin/mothership-darwin local --value global.ingress.domainName=example.com,global.domainName=example.com --components istio-configuration`
Expected result: Logs should say that `Reconcile action of istio-configuration triggered`
Actual result: Logs claim that `Reconcile action of istio triggered`, so not of `istio-configuration`.
Thoughts: Why does this logic not reconcile given component?

2. Reconciliation of `istio` component
Command used: `./bin/mothership-darwin local --value global.ingress.domainName=example.com,global.domainName=example.com --components istio`
Expected result: Error
Actual result: Logs should say that `Reconcile action of istio triggered`
Thoughts: There should be an error because there is no component `istio` available in Kyma resources. So how is it even possible to reconcile it?

There are some other problems with the code that I spotted but this summarises the most crucial part so far.

**Comment by mjakobczyk** [comment]
Retest after changes:
✅ 1. `actions registered for both istio-configuration & istio` - OK, there are two different actions registered
✅ 2. `implemented logic which determines whether to apply additional resources or not` - OK, `ReconcileAction` does not  trigger `deployIstioResources()` logic
✅ 3. ~~`README.md updated`~~ - README will be handled in a separate task
✅ 4. when `istio` component is not present in resources then error is thrown - OK, example log:
```bash
{"level":"WARN","time":"2022-02-02T08:40:02.017+0100","message":"Runner: failing reconciliation of 'istio' in version 'main' with profile 'evaluation': failed helm client render: loader failed to load helm chart: stat .workspace/main/resources/istio: no such file or directory"}
```

To me it looks decent now. ✅
