### ISSUE TITLE
Simplify and standardise integration test cases which require a DB (automated rollback etc.)

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#787]
**Description**

Currently is the implementation of unit-tests / integration test which require a DB not very intuitive as each test case has to case about establishing a proper data state (e.g. either the test has to be implemented in a way that it can deal with existing data, that the test is applying a cleanup before / after it was executed etc. etc.).

To simplify this situation, a new test strategy (e.g. by providing a framework or other appoach) which enables developers to run test cases without having a need to cleanup existing / the created data as part of their test logic.

AC:
* Unit tests / integration tests can use a DB without having a need to deal with existing / created data
* Usage of the the test approach is intuitive and simple and not increasing complexity

**Reasons**

Offer a simplified option to execute test cases which are using a DB without having a need to deal with existing / created data as part of the test logic

**Attachments**

**Comment by tobiscr** [comment]
POC here available: https://github.com/kyma-incubator/reconciler/pull/813

But needs further testing: also usage of separate DB schema for unit-tests should be introduced.

**Comment by jakobmoellersap** [comment]
Analysing @tobiscr POC and a few Frameworks to tackle our issues

**Comment by jakobmoellersap** [comment]
Review with @ruanxin resulted in the following:

- Decision to be made within the team wether we want to introduce a test suite one by one or in a big bang to avoid double maintenance
- We need a few examples of migrated tests so that the team can see how the tests can be migrated
- We should see wether it makes to allow for a containerfactory to be migratable and have some leeway in how we manage our containers
- Include a flag that allows us to initialize a DB migration into the container from schema files per Suite so that we can completely skip the shell script and run from a preinitialized database

Decision on Containers vs Embedded:
Chose Containers since it allows us independent parallel runtimes with containerized (independant) workloads, allowing parallel DB execution as well as later on volume bindings in case we want to mount in e.g. a staging db dump for certain tests against pseudo-prod data (@jeremyharisch fyi, this was what we talked about earlier today that needs to be done before we can include the CI cases for db migrations)
