### ISSUE TITLE
Cleanup cluster-config-status entities and deleted clusters

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#867]
**Description**

We are facing massive growth of cluster-config-status entities which lead on stage to a massive DB performance degradation.

https://console.cloud.google.com/sql/instances/kyma-mps-stage-730c/insights;duration=PT1H;sort_by=TOTAL_EXEC_TIME?project=sap-ti-dx-kyma-mps-stage&ref=https:%2F%2Faccounts.google.com%2F&pli=1&rapt=AEjHL4N58UTZ3Un3dmW8HByPqOU9hEDUf8jnnYAtYKPUK3VnHEO1r-cxLnhkTtkUBkYvAodNlGYkzDwIGmBynov20_bVA17WwA

This requires a fast enhancement of the existing housekeeping logic to ensure, that the amount of cluster-config-status entities isn't growing endless. Additionally, also deleted cluster entries should be dropped after a particular time.

AC: 

1. A cluster-config-status entity in the DB should be dropped when it is no longer referenced by a reconciliation entity

2. *Deleted* cluster entries (=cluster-entity + its cluster-config-entities + their cluster-config-status entities) should be deleted  after Y days.

This logic should become another cleanup-strategy of our cleaner-module in the mothership reconciler.

**Side note:** If possible, a first short-term solution in form of a SQL-script should be implemented to avoid outage-risks on our STAGE landscape

**Reasons**

Address identified scaling problems of STAGE database caused by huge amount of cluster-config-status entities.

**Attachments**

**Comment by veichtj** [comment]
Initial cleanup with following scripts is done:

[1_create_to_delete_views.sql.txt](https://github.com/kyma-incubator/reconciler/files/8154490/1_create_to_delete_views.sql.txt)
[2_delete_obsolete_config_statuses.sql.txt](https://github.com/kyma-incubator/reconciler/files/8154491/2_delete_obsolete_config_statuses.sql.txt)

**Comment by adityabhatia** [comment]
(* no longer referenced by a cluster configuration entity - check foreign key constraint)

**Comment by tobiscr** [comment]
Here a visualized view of the data - all orange entries can be dropped:
<img width="947" alt="Screen Shot 2022-03-22 at 17 52 03" src="https://user-images.githubusercontent.com/73824711/159534681-e4ca957c-28c6-4dcd-9761-154561140e78.png">

**Comment by adityabhatia** [comment]
Initial findings:
As a preliminary solution it is decided to implement through views, since the complexity is tedious to be implemented with the existing SQL framework. The views' performance was already tested on DEV db and it gave acceptable figures. To support the view implementation, new model entities would be required.

Due to inter relational foreign key dependencies; amongst clusters, configs, status, reconciliations and operations, it was decided remove to be deleted cluster status corresponding reconciliations first, to avoid foreign key constraint issues.

For deleted cluster entities, by default `20 days` is taken as a static value, which can be adjusted using the `reconciliations-max-age-days` flag

**Comment by adityabhatia** [comment]
Configuration of new feature flags: https://github.com/kyma-project/control-plane/pull/1488
