### ISSUE TITLE
Analyse impact of sidecar injection by default on Istio reconciliation

### ISSUE THREAD

**Issue by strekm** [kyma-incubator/reconciler#895]
**Description**

Analyse proces of installation / upgrade / reconciliation in terms of enabling sidecar injection by default. Process of Istio reconciliation is as follows (simplified):
1. install / upgrade Istio component with istioctl binary.
2. patch webhook configuration to enable sidecar injection
3. other required steps not important for this task.

Average time of Istio reconciliation takes around 90s. Mutating webhooks are created by istioctl itself. These objects are not created by Istio reconciler. Lets say we have following scenario: Istio is installed on a cluster, webhook is patched. after that without any changes to Istio component Istio reconciliation is run. Check if default Istio configuration is applied, which means webhooks are brought to original state before patching. Check what impact it has on Istio itself and on workloads with sidecars injected in terms of downtime. 

**Reasons**

Improving Istio reconciliation in terms of complexity and time.

**Attachments**

see also: https://github.com/kyma-project/kyma/issues/11637

**Comment by piotrkpc** [comment]
Performance overhead: Patching a webhook adding ~20 ms to the process so in that context it can be neglected.

Patching MutatingWebhookConfiguration creates potential race condition - rerunning istioctl apply brings back the default MutatingWebhookConfiguration so this could cause problems with Gardener hibernation process.

**Comment by piotrkpc** [comment]
Performance notes:
Without change. Version 2.1
```
{"level":"INFO","time":"2022-04-26T10:20:31.798+0200","message":"IstioPerformer.Version took: 147.269705ms"}
{"level":"INFO","time":"2022-04-26T10:20:32.034+0200","message":"IstioPerformer.Version took: 156.213823ms"}
{"level":"INFO","time":"2022-04-26T10:20:37.160+0200","message":"IstioPerformer.Update took: 5.125868709s"}
{"level":"INFO","time":"2022-04-26T10:20:37.176+0200","message":"IstioPerformer.PatchMutatingWebhook took: 16.196897ms"}
{"level":"INFO","time":"2022-04-26T10:20:37.408+0200","message":"IstioPerformer.Version took: 155.704734ms"}
{"level":"INFO","time":"2022-04-26T10:20:37.425+0200","message":"IstioPerformer.ResetProxy took: 17.156225ms"}
```
With change: disable ingressgw.
```
{"level":"INFO","time":"2022-04-26T10:39:38.804+0200","message":"IstioPerformer.Version took: 180.872843ms"}
{"level":"INFO","time":"2022-04-26T10:39:39.036+0200","message":"IstioPerformer.Version took: 149.020607ms"}
{"level":"INFO","time":"2022-04-26T10:39:43.903+0200","message":"IstioPerformer.Update took: 4.866710062s"}
{"level":"INFO","time":"2022-04-26T10:39:43.917+0200","message":"IstioPerformer.PatchMutatingWebhook took: 13.5102ms"}
{"level":"INFO","time":"2022-04-26T10:39:44.144+0200","message":"IstioPerformer.Version took: 153.934332ms"}
{"level":"INFO","time":"2022-04-26T10:39:44.162+0200","message":"IstioPerformer.ResetProxy took: 17.7272ms"}
```

In our tests Update step take consistently < 10s.
For update the longest step will be Update - since Proxy reset is most likely required it could take up to 5 minutes - timeout we have for the proxy reset.

**Comment by piotrkpc** [comment]
when trying to test scenario with enabling back ingress gateway I've discovered following bug.
https://github.com/kyma-incubator/reconciler/issues/1062

Another tests involved changing Istiod that required rollout of istiod. Reconcilation step is actively waiting for the resource. Similar things can be expected in case of ingress gateway.

```
{"level":"INFO","time":"2022-04-28T08:57:48.506+0200","message":"IstioPerformer.Version took: 134.942308ms"}
{"level":"INFO","time":"2022-04-28T08:57:48.702+0200","message":"IstioPerformer.Version took: 133.588354ms"}
{"level":"INFO","time":"2022-04-28T08:58:02.718+0200","message":"IstioPerformer.Update took: 14.016304551s"}
{"level":"INFO","time":"2022-04-28T08:58:02.733+0200","message":"IstioPerformer.PatchMutatingWebhook took: 14.625813ms"}
{"level":"INFO","time":"2022-04-28T08:58:32.958+0200","message":"IstioPerformer.Version took: 30.166379533s"}
```
A good improvement would be to export Prometheus metrics of our reconciliation process. Feature request: https://github.com/kyma-incubator/reconciler/issues/1063

**Comment by piotrkpc** [comment]
ProxyReset scenario - Update is much longer as expected. ProxyReset took ~12s - with 10 pods of httpbin. ProxyReset time variability is high, up-to 5 min timeout due to multiple factors that can impact the process:
- amount of workload
- performance of cluster that is running controllers that owns workload being rolled out
- performance of registry, caching configuration, network performance, etc.
Command: upgrade 2.1.3 to main:  `mothership-linux local --version main --components cluster-essentials,istio`
```
pkopec@piotr-nb kyma-incubator/reconciler (main *%) » cat timing-2.1.3-to-main-update.log | grep took                                                                                                                             130 ↵
{"level":"INFO","time":"2022-04-28T11:02:16.792+0200","message":"IstioPerformer.Version took: 121.185556ms"}
{"level":"INFO","time":"2022-04-28T11:02:16.977+0200","message":"IstioPerformer.Version took: 117.13337ms"}
{"level":"INFO","time":"2022-04-28T11:02:48.082+0200","message":"IstioPerformer.Update took: 31.10510676s"}
{"level":"INFO","time":"2022-04-28T11:02:48.100+0200","message":"IstioPerformer.PatchMutatingWebhook took: 18.350447ms"}
{"level":"INFO","time":"2022-04-28T11:02:48.281+0200","message":"IstioPerformer.Version took: 117.098258ms"}
{"level":"INFO","time":"2022-04-28T11:03:00.346+0200","message":"IstioPerformer.ResetProxy took: 12.06573178s"}
```

**Comment by piotrkpc** [comment]
Summary:
- `Update` and `ProxyReset` are likely to vary depending on external factors: amount of workload to be rolled-out or restored, peformance of cluster and network, described in detail in previous comments: [ProxyReset](https://github.com/kyma-incubator/reconciler/issues/895#issuecomment-1111951505), [Istiod and configuration change](https://github.com/kyma-incubator/reconciler/issues/895#issuecomment-1111827263), [normal reconcilation and disabeling of ingresgw](https://github.com/kyma-incubator/reconciler/issues/895#issuecomment-1109520280)
- `istioctl apply` overwrites the `MutatingWebhookConfiguration` - it causes the potential race condition that could impact Gardener hibernation process, the race condition time window = `Update` time + `PatchMutatingWebhook` time. Details in comment: [1](https://github.com/kyma-incubator/reconciler/issues/895#issuecomment-1109433663) and [2](https://github.com/kyma-incubator/reconciler/issues/895#issuecomment-1109520280)
- Side note: `Version` step after `Update` is inconsistent, possibly due to retries implemented in `istioctl` code that is waiting for resources. [Details](https://github.com/kyma-incubator/reconciler/issues/895#issuecomment-1111827263)

| Scenario                               | `IstioPerformer.Version` time elapsed | `IstioPerformer.Version` time elapsed | `IstioPerformer.Update` time elapsed | `IstioPerformer.PatchMutatingWebhook` time elapsed | `IstioPerformer.Version` time elapsed | `IstioPerformer.ResetProxy` time elapsed |
|----------------------------------------|---------------------------------------|---------------------------------------|--------------------------------------|----------------------------------------------------|---------------------------------------|------------------------------------------|
| no change                              | 147.269705ms                          | 156.213823ms                          | 5.125868709s                         | 16.196897ms                                        | 155.704734ms                          | 17.156225ms                              |
| disable ingress-gw                     | 180.872843ms                          | 149.020607ms                          | 4.866710062s                         | 13.5102ms                                          | 153.934332ms                          | 17.7272ms                                |
| change istiod - rollout required       | 134.942308ms                          | 133.588354ms                          | 14.016304551s                        | 14.625813ms                                        | 30.166379533s                         | 21.619424ms                              |
| change update - proxy reset 10xhttpbin | 121.185556ms                          | 117.13337ms                           | 31.10510676s                         | 18.350447ms                                        | 117.098258ms                          | 12.06573178s                             |
