### ISSUE TITLE
Refactoring our DB Model for easier access of Reconciliation and Inventory Data without having to rely on duplicate/aggregate keys and views

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-incubator/reconciler#921]
Description:

When we want to access our data for inventory or reconciliations we are currently using a historically grown model with various optimization potential and better lookup possibilities. We want to consolidate this into a new Relational Model that better fits our reconciliation use cases and can scale out better.

AC:

- Create an ER Model and discuss it with the team for optimizations
- Create Migration SQL together with a testable data migration that ensures we have a stable migration path into the new Model
- Swap the existing Views and Tables in the reconciler to instead use the new tables and views
- Make sure that we have a proper Regression test

Reasons: 
Having a scalable and condensed DB model improves performance and is able to help developers better understand our data load. It also allows us to extend the model as needed.

**Comment by jeremyharisch** [comment]
We came up with several models for refactoring the DB model:

1. Only Introducing new PKs and get rid of combined PKs
![Reconciler_DB_new_PKs](https://user-images.githubusercontent.com/48282931/158991495-78a6e438-8d75-4a65-b7de-df846dde6ebb.svg)
2. Having an audit table for the cluster statuses and keep track of the current status of the cluster in the cluster config table
![Reconciler_DB_with_Audit_Status_Table](https://user-images.githubusercontent.com/48282931/158991500-08469753-30bd-4a45-8c46-2f9d78f7be25.svg)
3. Having shadow tables for the cluster configs and the clusters, to get rid of the versioned tables to always work only on tables with the latest data
![Reconciler_DB_with_Shadow_Tables](https://user-images.githubusercontent.com/48282931/158991502-cdb0dd68-7a17-4d63-af32-705f063f7c81.svg)

Due to the future scope of how the architecture will look like, we decided to drop the investigation for now due to several internal reasons. Thus, I will not go into the details of each model.

For further questions, please reach out to me.
